//************************************************************************************
//*                                                                                  *
//* ===== DO NOT EDIT =====                                                          *
//* Any change will be overwritten                                                   *
//* Generated by github.com/boundedinfinity/enumer                                   *
//*                                                                                  *
//************************************************************************************

package schema_type

import (
	"encoding/json"
	"errors"
	"fmt"

	"github.com/boundedinfinity/commons/slices"
)

var (
	All = []SchemaType{
		String,
		Float,
		Double,
		Integer,
		Byte,
		Char,
		Short,
		Long,
		Ubyte,
		Ulong,
		Ushort,
		Object,
		Array,
		Boolean,
		Enum,
		Date,
		Time,
		DateTime,
		Duration,
	}
)

func (t SchemaType) String() string {
	return string(t)
}

func Parse(v string) (SchemaType, error) {
	f, ok := slices.FindFn(All, func(x SchemaType) bool {
		return SchemaType(v) == x
	})

	if !ok {
		return f, ErrorV(v)
	}

	return f, nil
}

func Is(s string) bool {
	return slices.ContainsFn(All, func(v SchemaType) bool {
		return string(v) == s
	})
}

var ErrInvalid = errors.New("invalid enumeration type")

func ErrorV(v string) error {
	return fmt.Errorf(
		"%w '%v', must be one of %v",
		ErrInvalid, v, slices.Join(All, ","),
	)
}

func (t SchemaType) MarshalJSON() ([]byte, error) {
	return json.Marshal(string(t))
}

func (t *SchemaType) UnmarshalJSON(data []byte) error {
	var v string

	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}

	e, err := Parse(v)

	if err != nil {
		return err
	}

	*t = e

	return nil
}

func (t SchemaType) MarshalYAML() (interface{}, error) {
	return string(t), nil
}

func (t *SchemaType) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var v string

	if err := unmarshal(&v); err != nil {
		return err
	}

	e, err := Parse(v)

	if err != nil {
		return err
	}

	*t = e

	return nil
}
